<a href="https://colab.research.google.com/github/yangy29/hello-world/blob/master/hm02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Python Exercises

![](https://github.com/rpi-techfundamentals/hm-01-starter/blob/master/notsaved.png?raw=1)

**WARNING!!!  If you see this icon on the top of your COLAB sesssion, your work is not saved automatically.**

**Save your working file in Google drive so that all changes will be saved as you work. MAKE SURE that your final version is saved to GitHub.** 

Before you turn this in, make sure everything runs as expected. First, restart the kernel (in the menu, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment.

**You may find it useful to go through the notebooks from the course materials when doing these exercises.**

**If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

In [0]:
files = "https://github.com/rpi-techfundamentals/hm-02-starter/raw/master/files.zip"
!pip install git+https://github.com/data-8/Gofer-Grader && wget $files && unzip -o files.zip

In [0]:
#This loads the grading software.  If you later get a "failed to import OK.py" you need to rerun.
from client.api.notebook import Notebook
ok = Notebook('hm02.ok')
_ = ok.auth(inline=True)

## Exercise-Packages

This creates an Numpy array. Numpy is a common package that we will use to work with arrays. You can read more about Numpy [here](http://www.numpy.org/). 

```
a = np.array([2,3,4])
print(a)
```

To get this to work, you will have to make sure that the numpy(np) package is installed. 

(1) Verify that Numpy is installed. How did you know?  
Describe how you would you install it if it wasn't installed?


In [172]:
man1="""

"""
!pip install numpy
import numpy as np

(2) Fix the cell below so that `a` is a `numpy` array.

In [162]:
#Fix this code of q2. 
a = np.array([5,6,7,8])
print(a, type(a))


[5 6 7 8] <class 'numpy.ndarray'>


In [163]:
_ = ok.grade('q02')

(3) Create a numpy array `b` with the values `12, 13, 14, 15`.



In [0]:
#<insert q3 code here>
b = np.array([12,13,14,15])



In [174]:
_ = ok.grade('q03')

## Exercise - Operations on Variables

(4) Describe what happens when you multiply an integer times a boolean? 
What is the resulting type? Provide examples.


In [175]:
#You must assign your answer to q4_answer. 
man4="""
If the boolean is True, the answer is the integer itself; If the boolean is False, the answer is 0.
"""
c = 2
d = False
c*d

0

(5) Describe happens when you try to multiply an integer value times a null?

In [0]:
man5="""
It cannot be operated.
"""



(6) Take 5 to the power of 4 and assign it to a variable `c`. Then transform the variable `c` to a type `float`. 

In [177]:
#<insert q6 code here>
c = 5**4
c = float(c)
c

625.0

In [178]:
_ = ok.grade('q06')

## Exercise-Lists
Hint: [This link is useful.](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) as is the process of tab completion (using tab to find available methods of an object).

(7) Create a list `elist1` with the following values `1,2,3,4,5`.<br>


In [179]:
#<insert q7 code here>
elist1 = [1,2,3,4,5]
elist1


[1, 2, 3, 4, 5]

In [180]:
_ = ok.grade('q07')

(8) Create a new list `elist2` by first creating a copy of `elist1` and then reversing the order.

*HINT, remember there is a specific function to copy a list.* 


In [0]:
#<insert q8 code here>
elist3 = elist1.copy()
elist3
elist2 = list(reversed(elist3))


In [182]:
_ = ok.grade('q08')

(9) Create a new list `elist3` by first creating a copy of `elist1` and then adding `7, 8, 9` to the end. (Hint: Search for a different function if appending doesn't work.) 

In [183]:
#<insert q9 code here>
elist3 = elist1.copy()
elist3.append(7)
elist3.append(8)
elist3.append(9)
elist3


[1, 2, 3, 4, 5, 7, 8, 9]

In [184]:
_ = ok.grade('q09')

(10) Create a new list `elist4` by first creating a copy of `elist3` and then insert `6` between `5` and `7`.

In [185]:
#<insert q10 code here>
elist4 = elist3.copy()
elist4.insert(5,6)
elist4


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [186]:
_ = ok.grade('q10')

## Exercise-Sets/Dictionary

This [link to documentation on sets](https://docs.python.org/3/tutorial/datastructures.html#sets) may be useful.

(11) Create a set `eset1` with the following values (1,2,3,4,5).


In [187]:
#<insert q11 code here>
eset1 = set([1,2,3,4,5])
eset1


{1, 2, 3, 4, 5}

In [188]:
_ = ok.grade('q11')


(12) Create a new set `eset2` the following values (1,3,6).



In [189]:
#<insert q12 code here>
eset2 = set([1,3,6])
eset2



{1, 3, 6}

In [190]:
_ = ok.grade('q12')

(13) Create a new set `eset3` that is `eset1-eset2`.



In [191]:
#<insert q13 code here>
eset3 = eset1-eset2
eset3

{2, 4, 5}

In [192]:
_ = ok.grade('q13')

(14) Create a new set `eset4` that is the union of `eset1+eset2`.


In [193]:
#<insert q14 code here>
eset4 = eset1.union(eset2)
eset4

{1, 2, 3, 4, 5, 6}

In [194]:
_ = ok.grade('q14')


(15) Create a new set `eset5` that includes values that are in both `eset1` and `eset2` (intersection).



In [195]:
#<insert q15 code here>
eset5 = eset1.intersection(eset2)
eset5

{1, 3}

In [196]:
_ = ok.grade('q15')

(16) Create a new dict `edict1` with the following keys and associated values: st1=45; st2=32; st3=40; st4=31.

*Hint: There is a good section on dictionaries [here](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).


In [197]:
#<insert q16 code here>
edict1 = {"st1":45,"st2":32,"st3":40,"st4":31}
edict1


{'st1': 45, 'st2': 32, 'st3': 40, 'st4': 31}

In [198]:
_ = ok.grade('q16')


(17) Create a new variable `key1` where the value is equal to the value of dictionary edict1 with key `st3`.

In [0]:
#<insert q17 code here>
key1 = edict1["st3"]

In [200]:
_ = ok.grade('q17')

# Exercise-Numpy Array

(18) Create a new numpy array `nparray1` that is 3x3 and all the number 3 (should be integer type).



In [201]:
#<insert q18 code here>
nparray1 = np.full((3,3),3)
nparray1


array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [202]:
_ = ok.grade('q18')


(19) Create a new variable `nparray1sum` that sums all of column 0.


In [203]:
#<insert q19 code here>
nparray1sum = np.sum(nparray1,axis=0)[0]
nparray1sum

9

In [204]:
_ = ok.grade('q19')

(20) Create a new variable `nparray1mean` that takes the average of column 0.


In [0]:
#<insert q20 code here>
nparray1mean = np.mean(nparray1,axis=0)[0]


In [206]:
_ = ok.grade('q20')

(21) Create a new numpy array `nparray2` that selects only column 1 of `nparray1` (all rows).


In [207]:
#<insert q21 code here>
nparray2 = nparray1[:,0:1]
nparray2


array([[3],
       [3],
       [3]])

In [208]:
_ = ok.grade('q21')

(22) Create a new numpy array `nparray3` that is equal to `nparray1` times `2` (you should not alter `nparray1`).


In [209]:
#<insert q22 code here>
nparray3 = nparray1 * 2
nparray3


array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [210]:
_ = ok.grade('q22')

(23) Create a new numpy array nparray4 that is a verticle stack of `nparray1` and `nparray3`.

In [211]:
#<insert q23 code here>
nparray4 = np.row_stack((nparray1,nparray3))
nparray4

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [212]:
_ = ok.grade('q23')

## Exercise-Pandas

For these you will need to import the iris dataset. You should find the file `iris.csv` in the main directory.  

While we showed 2 ways of importing a csv, you should use the `read_csv` method of Pandas to load the csv into a dataframe called `df`. 


In [0]:
#Load iris.csv into a Pandas dataframe df here.
#Check out the first few rows with the head command. 
import pandas as pd
df = pd. read_csv("iris.csv")
df


(24) Create a variable `df_rows` that includes the number of rows in the `df` dataframe.

In [214]:
#<insert q24 code here>
df_rows = len(df.iloc[:,1])
df_rows

150

In [215]:
_ = ok.grade('q24')

(25) Create a new dataframe `df_train` that includes the first half of the `df` dataframe. Create a new dataframe `df_test` that includes the second half. 

In [0]:
#<insert q25 code here>
df_train = df.iloc[:75,:]
df_test = df.iloc[75:150,:]


In [217]:
_ = ok.grade('q25')

(26) Create a new Pandas Series `sepal_length` from the `sepal_length` column of the df dataframe.

In [0]:
#<insert q26 code here>
sepal_length = pd.Series(df.iloc[:,0])
#sepal_length


In [219]:
_ = ok.grade('q26')


(27) Using, the Iris dataset, find the mean of the `sepal_length` series in our sample and assign it to the `sepal_length_mean` variable. You should round the result to 3 digits after the decimal. 

```
#Round example
a=99.9999999999999
#For example, the following will round a to 2 digits.
b = round(a,2)   

```

In [220]:
#<insert q27 code here>
sepal_length_mean = round(pd.Series.mean(sepal_length),3)
sepal_length_mean


5.843

In [221]:
_ = ok.grade('q27')

## Enter your Information
Enter your information.  This will run all tests to make sure that the assignment is complete. 

In [0]:
course="mgmt6560"   #course number
section=""          #section 
first_name="Yulan"   #For example, "jason"
last_name="Yang"    #For example, "kuruzovich"
student_id="yangy29"       #for example "kuruzj"
student_email="yangy29@rpi.edu"    #for example "kuruzj@rpi.edu"
collaborators = ""  #You can speak with others regarding the assignment, but all typed work must be your own.

In [223]:
#This runs all tests. 
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]